# These are supported funding model platforms

github: robertsLando
patreon: user?u=16906849
liberapay: robertsLando
custom: [paypal.me/daniellando, "https://www.amazon.it/hz/wishlist/ls/2LYWFKB0WTSNN?ref_=wl_share"]
