name-template: "Release $RESOLVED_VERSION 🚀"
tag-template: "v$RESOLVED_VERSION"
replacers:
  - search: '/(fix(\([^)]+\)){0,1}: )|(feat(\([^)]+\)){0,1}: )|(chore(\([^)]+\)){0,1}: )|(docs(\([^)]+\)){0,1}: )/g'
    replace: ""
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "⛏️ Chore"
    label: "chore"
  - title: "📚 Docs"
    label: "docs"
  - title: "🤖 Bumped deps"
    labels:
      - "prod-dependencies"
      - "deps"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
autolabeler:
  - label: "docs"
    title:
      - "/^docs/"
  - label: "bug"
    title:
      - "/^fix/"
  - label: "feature"
    title:
      - "/^feat/"
  - label: "chore"
    title:
      - "/^chore:/"
template: |
  ## What's Changed

  $CHANGES
