queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - label=automerge

pull_request_rules:
  - name: automatic merge dependabot
    conditions:
      - base=master
      - author=dependabot[bot]
      - label!=major
    actions:
      queue:
        method: squash
        name: default

  - name: approve dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        message: 'Thanks Dependabot! :rocket:'
