name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |2-
          **BEFORE** opening an issue, please read and follow these steps:

          1. Are you using HomeAssistant?
          If yes, please open your issue at https://github.com/home-assistant/core/issues
          UNLESS a developer told you to come here.

          2. Is your issue related to a device not working as expected?
          If yes, please open an issue at: https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=&template=bug_report.yml

          3. Check the troubleshooting section if your problem is described there:
          https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report

          4. Check the changelog if your problem was already fixed recently.
          https://github.com/zwave-js/zwavejs2mqtt/blob/master/CHANGELOG.md
          We cannot provide support if you are not using the latest version.

          5. Make sure to provide the necessary information, as described here:
          https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report

          If you are using HomeAssistant, this is how you do it:

         Home Assistant -> settings -> Integrations -> Z-Wave JS -> Configure -> Create dump -> zip the json file and post it here.


        Thanks, now on to your issue:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: ' I am not using Home Assistant. Or: a developer has told me to come here.'
        - label: >-
            I have checked the troubleshooting section and my problem is not
            described there.
        - label: I have read the changelog and my problem is not mentioned there.
  - type: dropdown
    id: build
    attributes:
      label: Deploy method
      description: How did you installed Zwavejs2mqtt
      options:
        - Docker
        - PKG executable
        - Snap
        - Manually built (git clone - yarn build - yarn install
    validations:
      required: true
  - type: input
    id: zjs2m-version
    attributes:
      label: Zwavejs2Mqtt version
    validations:
      required: true
  - type: input
    id: zjs-version
    attributes:
      label: ZwaveJS version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      placeholder: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://www.issue-forms-creator.app/)
