contact_links:
  - name: 💡 Feature Request
    url: https://github.com/zwave-js/zwave-js-ui/discussions/new
    about: Share ideas for new features
  - name: ❓ Question
    url: https://github.com/zwave-js/zwave-js-ui/discussions/new
    about: General questions