name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout zwavejs2mqtt
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ matrix['node-version'] }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install node modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        if: matrix['node-version'] == '14.x'
        run: yarn run lint

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2.1.4
        with:
          path: dist
          key: ${{ matrix['node-version'] }}-cache-build-${{ hashFiles('build/*') }}-${{ hashFiles('src/*') }}-${{ hashFiles('static/*') }}-${{ hashFiles('yarn.lock') }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Generate coverage report
        if: matrix['node-version'] == '14.x'
        run: |
          yarn run coverage
          yarn run record-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix['node-version'] == '14.x'
        with:
          github-token: ${{ secrets.github_token }}
