name: ci

on:
  push:
    branches:
      - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout Z-Wave JS UI
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        if: matrix['node-version'] == '14.x'
        run: yarn run lint

      - name: Prepare lint auto-fix patch
        if: |
          matrix['node-version'] == '14.x' &&
          failure() &&
          github.event_name == 'pull_request'
        id: lint
        run: |
          # Run all lint commands and abort if one has unfixable errors
          yarn run lint-fix
          git diff --name-only || true
          if ! git diff --quiet ; then
            echo "has changes"
            git diff > fix.patch
            echo "::set-output name=changed::true"
          else
            echo "unchanged"
            echo "::set-output name=changed::false"
          fi
      - name: Upload Patch
        if: |
          matrix['node-version'] == '14.x' &&
          failure() &&
          github.event_name == 'pull_request' &&
          steps.lint.outputs.changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: lint-fix
          path: fix.patch

      - name: Test
        run: yarn run test

      - name: Generate coverage report
        if: matrix['node-version'] == '14.x'
        run: |
          yarn run coverage
          yarn run record-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix['node-version'] == '14.x'
        with:
          github-token: ${{ secrets.github_token }}
