name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: zwavejs/zwavejs2mqtt
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          tag-custom: ${{ github.ref == 'refs/heads/master' && 'dev' || '' }}
          label-custom: |
            org.opencontainers.image.vendor=zwave-js
            org.opencontainers.image.documentation=https://zwave-js.github.io/zwavejs2mqtt/#/
            org.opencontainers.image.authors=Daniel Lando <daniel.sorridi@gmail.com>
            org.opencontainers.image.url=https://zwave-js.github.io/zwavejs2mqtt/#/
            maintainer=robertsLando
      - name: build+push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:sha-${{ env.GITHUB_SHA }}
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
