name: Docker Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  docker-arm64:
    name: linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - uses: actions/github-script@v3
        id: ref-sanitized
        with:
          script: |
            const ref = context.ref
            return ref.replace(/^refs\/heads\/|-/, '')

      - name: Create Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: zwavejs/zwavejs2mqtt
          tag-sha: false
          tag-latest: false
          label-custom: |
            org.opencontainers.image.vendor=zwave-js
            org.opencontainers.image.documentation=https://zwave-js.github.io/zwavejs2mqtt/#/
            org.opencontainers.image.authors=Daniel Lando <daniel.sorridi@gmail.com>
            org.opencontainers.image.url=https://zwave-js.github.io/zwavejs2mqtt/#/
            maintainer=robertsLando

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ steps.ref-sanitized.outputs.result }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ steps.ref-sanitized.outputs.result }}-${{ github.sha }}
            buildx-${{ steps.ref-sanitized.outputs.result }}
            buildx-

      - name: Buildx build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          file: docker/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
